### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lorg/apache/logging/log4j/LogManager

### ISSUE THREAD

**Issue by FutureHere** [Guardsquare/proguard#326]
After upgrade Proguard version 6.0.3 to 7.3.0
apk crash 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/15063013/227454103-29aa8180-6072-4487-bb5f-960ba20d2e72.png">

mapping:

proguard.optimize.gson._GsonUtil -> b.a.a.a:
 {"fileName":"_GsonUtil.java","id":"sourceFile"}
    org.apache.logging.log4j.Logger logger -> a
    43:43:void <init>() -> <init>
    63:75:com.google.gson.TypeAdapter getTypeAdapter(com.google.gson.Gson,java.lang.Class,java.lang.Object) -> a
    95:108:com.google.gson.TypeAdapter getTypeAdapter(com.google.gson.Gson,com.google.gson.reflect.TypeToken,java.lang.Object) -> a
    116:120:java.lang.reflect.Type getRuntimeTypeIfMoreSpecific(java.lang.reflect.Type,java.lang.Object) -> a
    131:131:boolean isCustomTypeAdapter(com.google.gson.TypeAdapter) -> a
    45:45:void <clinit>() -> <clinit>

I think the reason is Gson optimization

can u help me ? Thanks

**Comment by FutureHere** [comment]
![image](https://user-images.githubusercontent.com/15063013/227453771-7922ebff-c200-480f-995d-95b513c72db8.png)

**Comment by mrjameshamilton** [comment]
Hi @FutureHere ! 

Can you try to narrow down the issue by disabling ProGuard features and/or adding keep rules?

For example: you can disable GSON optimization with `-optimizations !library/gson` (see https://www.guardsquare.com/manual/configuration/optimizations)

You can also try disabling obfuscation, optimization and shrinking generally to see if one of those are causing the problem: `-dontshrink`, `-dontobfuscate`, `-dontoptimize`

You can also try adding keep rules for the missing class.

If you cannot solve the issue via configuration, can you provide a reproducible sample?

**Comment by FutureHere** [comment]
> Hi @FutureHere !
> 
> Can you try to narrow down the issue by disabling ProGuard features and/or adding keep rules?
> 
> For example: you can disable GSON optimization with `-optimizations !library/gson` (see https://www.guardsquare.com/manual/configuration/optimizations)
> 
> You can also try disabling obfuscation, optimization and shrinking generally to see if one of those are causing the problem: `-dontshrink`, `-dontobfuscate`, `-dontoptimize`
> 
> You can also try adding keep rules for the missing class.
> 
> If you cannot solve the issue via configuration, can you provide a reproducible sample?

How can i use proguard without log4j ?
i find the problem proguard  dependent org.apache.logging.log4j and change the app code In proguard process
but my application not dependent log4j, so  the crash that Noclassdefound log4j happened.

we cant dependent log4j in our app ,so How can i use proguard without log4j ? Whether it can be set？

**Comment by FutureHere** [comment]
> Hi @FutureHere !
> 
> Can you try to narrow down the issue by disabling ProGuard features and/or adding keep rules?
> 
> For example: you can disable GSON optimization with `-optimizations !library/gson` (see https://www.guardsquare.com/manual/configuration/optimizations)
> 
> You can also try disabling obfuscation, optimization and shrinking generally to see if one of those are causing the problem: `-dontshrink`, `-dontobfuscate`, `-dontoptimize`
> 
> You can also try adding keep rules for the missing class.
> 
> If you cannot solve the issue via configuration, can you provide a reproducible sample?

How can i use proguard without log4j ?
i find the problem proguard  dependent org.apache.logging.log4j and change the app code In proguard process
but my application not dependent log4j, so  the crash that Noclassdefound log4j happened.

we cant dependent log4j in our app ,so How can i use proguard without log4j ? Whether it can be set？

**Comment by FutureHere** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/15063013/228436771-ae987639-55cb-4571-b9ab-53d6cbcc20c8.png">

-optimizations !library/gson

**Comment by FutureHere** [comment]
addConfigurationDebugging?

**Comment by mrjameshamilton** [comment]
Thanks for the extra information! It looks like log4j loggers were accidentally added to code that is injected into the app for GSON optimization and configuration debugging. Should be solved by #328
